Alcor_Performance_Report
futurewei-cloud/alcor-perf pull request #16
Opened 2022-03-07 10:37 UTC by yanmo96

Alcor Performance Report.
Still need to add a bit more info.
Please let me know if anything need to be changed.
Thanks

2022-03-15 18:11 UTC, cj-chung requested changes

2022-03-15 18:11 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +# Introduction
@yanmo96 Please put TOC (Table of Content) and their link to the section in the beginning of the report.

2022-03-15 18:38 UTC, cj-chung requested changes

2022-03-15 18:38 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 Performance Test Setup

2022-03-15 18:41 UTC, cj-chung requested changes

2022-03-15 18:41 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| 80            | 755.5GB     | 730GB                 |
@yanmo96 Please give it one more column before "VCPUs" to indicate the Number or name for computer node, such as "compute1", "compute2", etc.

2022-03-15 19:05 UTC, cj-chung requested changes

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 It's better rename this section to "Performance Test Cases and Scenarios" and briefly describe what test cases and scenarios we tested.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +## API Test, Port:
@yanmo96 add a upper level section header "Performance Test Result" before "API Test, Port". Rename "API Test, Port" to "Alcor API Test for Port creation and list"

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 do you have paragraphs to explain the result listed in the table and figure?

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 Please give one or two paragraphs to explain the data listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 Rename this title to "Alcor API Test for Subnet creation and list".

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| Max   | 213.156499 | 207.863239 | 208.112991 | 237.870493 | 204.961099 |
@yanmo96 Please give one or two paragraphs to explain the results listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| Max   | 168.864333 | 196.305945 |         | 202.222719 | 194.40302  |
@yanmo96 Please give one or two paragraphs to explain the results listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| Max   |        | 230.72542  | 239.914779 | 212.821755 | 204.047763 |
@yanmo96 Please give one or two paragraphs to explain the results listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| Max   | 180.997654 | 190.303224 | 211.520134 | 223.21284  | 211.6647   |
@yanmo96 Please give one or two paragraphs to explain the results listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 Rename the title to "Alcor API Test for VPC creation".

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| ![](images/vpc_qps.png) | ![](images/vpc_qps_p.png) |
@yanmo96 Please give one or two paragraphs to explain the results listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 Rename the title to "End-to-end VM creation Test for Small VPC scenario" and please give a paragraph to explain what is the small VPC.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +## End-to-end Test, Big VPC:
@yanmo96 Rename the title to "End-to-end VM creation Test for Large VPC scenario" and please give a paragraph to explain what is the large VPC.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| run 5 | 0.97742867 |
@yanmo96 Please give one or two paragraphs to explain the results listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +| run 3 | 0.43146736 |
@yanmo96 Please give one or two paragraphs to explain the results listed in the table and figure.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +
@yanmo96 Please rename the title to "End-to-end VM creation Test for Multiple Port per VM scenario" and give a paragraph to explain the scenario.

2022-03-15 19:05 UTC, cj-chung commented on benchmark/AlcorPerformanceTestReport/README.md
> +![](images/alcor-port_9n-10s-10p-10t-10c_run1-2022-03-05_00-41-28.json_boxplot.png)
Please give one or two paragraphs to explain the results in the figure.

2022-03-15 19:10 UTC, cj-chung commented
@yanmo96 Please go through the report again to fix some grammar and grammatical tense issues. You use Future tense a lot in the report, but actually you've done most of the future tense sentences in the report.

2022-03-17 08:49 UTC, yanmo96 commented
> @yanmo96 Please go through the report again to fix some grammar and grammatical tense issues. You use Future tense a lot in the report, but actually you've done most of the future tense sentences in the report.

Will make the above changes! Thanks for the feedback!

2022-04-12 18:01 UTC, cj-chung commented
@yanmo96 Please put the date or duration you conduct these test in the overview section.

2022-04-12 21:26 UTC, yanmo96 commented
> 

Hi James, I have added in the changes. Thanks

2022-04-13 20:39 UTC, cj-chung approved these changes
LGTM

2022-11-14 17:07 UTC, xieus approved these changes

2022-11-14 17:07 UTC, merged